### ISSUE TITLE
Filecoin download in the gateway is returning metadata instead of the file

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/gateway#127]
Something changed recently with the estuary api and when downloading a file the gateway is actually returning only metadata about the file.

We need to fix the python filecoin drivers.

**Comment by mrsmkl** [comment]
At least in my test it just returns the file, need more info...

**Comment by r-marques** [comment]
Did you test with the old gateway?
@josepablofm78 can show you what the problem is in the defi marketplace

**Comment by josepablofm78** [comment]
@mrsmkl  , Maybe the difference is CLI vs Browser

We are using  sdk.nfts.access(assetDid, account) to download the asset. 
If we don't add a path as a parameter, it seems the sdk uses the js-file-download lib to allow downloads from a browser:
https://github.com/nevermined-io/sdk-js/blob/master/src/nevermined/utils/WebServiceConnector.ts#L117

(Maybe it not a difference at all, because both options, fs and js-file-download, use the same response object)

As Rod commented, instead of downloading the file itself we are getting a metadata file
We are using  https://defi.v2.gateway.mumbai.nevermined.rocks/  as gateway, and it's configured with  https://api.estuary.tech/ as Estuary endpoint

Also, since last week I'm not able to publish any new file to filecoin (it was working perfectly fine). We are posting a file object to https://defi.v2.gateway.mumbai.nevermined.rocks/api/v1/gateway/services/upload/filecoin but now we get an error

**Comment by mrsmkl** [comment]
Perhaps api.estuary.tech is the problem (at least for uploads). I'm using shuttle-4.estuary.tech

**Comment by r-marques** [comment]
> Perhaps api.estuary.tech is the problem (at least for uploads). I'm using shuttle-4.estuary.tech

@josepablofm78 can you try this?

**Comment by r-marques** [comment]
same problem with `shuttle-5.estuary.tech`
